### ISSUE TITLE
Discussion to get the best idea

### ISSUE THREAD

**Issue by mohamedabdallah43** [mohamedabdallah43/SE2018G05#1]

**Comment by mohamedabdallah43** [comment]
ي ريت ي شباب كل واحد يسيب فكرته هنا ونبدأ نتناقش لحد ما نشوف افضل فكرة إن شاء الله :"D

**Comment by MohamedKhaled30** [comment]
انا فكرت اننا ممكن نعمل زي محرك بحث بالنسبة للي مهتميين بالدراسة اون لاين مثلا او للي عايز اي كورس  
بحيث نخلي مثلا اللي داخل يسجل و يكتب الحاجات او الكورسات او اللغات اللي هو مهتم بيها كل ده و هو بيسجل 
 ونكوون مجمعين شوية كورسات كده من يوديمي و كورسيرا و اليوتيوب الكورسات فري حاسس انها بسيطة بس اشطة اهي فكرة برده :"D

**Comment by mohamedabdallah43** [comment]
عاش حلو وممكن كمان نزود يجيله فرص الشغل فالمجالات اللي كاتبها فبروفايله وممكن نزود عليه كذا حاجة مع الوقت، نشوف الباقيين بس :'D

**Comment by DinaEzz** [comment]
انا فكرت اننا نعمل سايت شبه امازون كده بحيث ان اليوزر ممكن يشتري او يبيع الحاجه مستعمله عنده

**Comment by mohamedabdallah43** [comment]
حلو، وانا فكرتي أن ممكن نعمل سايت لطلبة الكلية بحيث أن لكل واحد هيبقى ليه بروفايل عليه وطبعا هيبقى منقسم حسب قسم كل واحد وهيبقى عليه كل حاجة تخصص المجال دا من كورسات وسوق عمله عامل ازاي ومحاضرات كلية أو جداول وكل حاجة وكمان يبقي ف مكان لطرح الاسئلة ويبقى فيها مكان زي سكتش كدا لو حد عاوز ينزل سؤال أو يجاوب ع سؤال برسمه زي الالكترونكس او ايا كان ودا مش كل حاجة هيبقى ف اضافات كتير جدا هتساعد الطلبة وتقلل التوهان وبالذات لطلبة اعدادي، نستني فكرة هديل ونشوف الفكرة أن شاء الله اللي هنقرر نبدأ فيها وهنبدأ كلنا نفكر فيها ونطلعها بأفضل شكل إن شاء الله :')

**Comment by hadeelashraf** [comment]
انا فكرت ان احنا نعمل زي موقع لتنمية المواهب كدة .. المستخدم بيدخل يسجل بياناته والمجال اللي هوا مهتم بيه زي الشعر او الرسم او كدة ويقدر يدخل ع كورسات للموهبة ده واشهر الناس فيها واعمالهم ويبقا ليه عندنا بروفايل يقدر يعرض فيه اعماله حاساها هتبقى حاجة مفيدة ومش معمولة قبل كدة وهنساعد بيها الناس العادية انها تنمي موهبتها ويبقا ليها مكان تعرض فيه اعمالها ممكن اصلا بعد كدة يجيلهم فرص شغل من بروفايلتهم او ناس تتشتري رسوماتهم  وهكذا
